### PR TITLE
[Travis CI] Prefer Source

### PR DESCRIPTION
**Pull request by JHGitty**

### CODE REVIEW

**Comment by DRvanR** [comment]
Why would `prefer-source` be better? `prefer-dist` is used since this utilizes the local travis caches for composer repo's. Furthermore the composer documentation states "[This can speed up installs substantially on build servers and other use cases where you typically do not run updates of the vendors][1]", which helps if the local travis cache fails.

For now not convinced this change would be an improvement, but am interested in why this would be better.

[1]: https://getcomposer.org/doc/03-cli.md#install

**Comment by JHGitty** [comment]
@DRvanR Currently it mostly use the ``source`` and not the ``dist``:
https://travis-ci.org/SURFnet/yubikey-api-client-bundle/jobs/98492745

Example:
```
Failed to download symfony/event-dispatcher from dist: Could not authenticate against github.com
Now trying to download from source
```

**Comment by DRvanR** [comment]
That happens because of the rate limiting of Github which is being triggered by Travis, causing composer to fall back to using dist. That does not mean it happens every build, nor that it will be better to use as default. The rate limiting kicking in has been a recurring issue with Travis that has been discussed with them at length (and is less of an issue for their paid service I must admit).

They do however recommend to keep using `dist` as that allows them to cache those libs locally (inside their network) which could alleviate this issue. Seeing this change goes against the advice of both composer and Travis, I do not think this should be merged.

**Comment by JHGitty** [comment]
Ok, good to know - thanks! :+1: I'll try to push this message to other bundles :smile:

**Comment by xabbuh** [comment]
You should however change the directory to be cached to `~/.composer/cache/files` to prevent the cache from being invalidated too often.

**Comment by xabbuh** [comment]
see #14

**Comment by JHGitty** [comment]
@DRvanR Are you sure? This user say something else here: https://github.com/guzzle/guzzle/pull/1468#issuecomment-217251743
Please check this out. Is ``--prefer-dist`` or ``--prefer-source`` better?

**Pull request closed without merging**
