### PR TITLE
Add HHVM to Travis CI

### PR DESCRIPTION
**Pull request by JHGitty**
#13

### CODE REVIEW

**Comment by DRvanR** [comment]
As discussed in #13, there currently is no pressing reason to formally support HHVM. However, it could be added as allowed failure to ease possible future support. This requires that the `.travis.php.ini` file is not added for the HHVM environment.

**Comment by JHGitty** [comment]
@DRvanR Travis CI build was successful. :+1:

**Comment by DRvanR** [comment]
Awesome! Could you please add it as allowed failure? Until HHVM is a target platform, it should not be allowed to break the build.

**Comment by JHGitty** [comment]
@DRvanR done. :+1:

**Comment by Huskynarr** [comment]
:+1:

**Comment by DRvanR** [comment]
Great work, much appreciated!

**Pull request merged**
