### PR TITLE
Delete composer.lock

### PR DESCRIPTION
**Pull request by JHGitty**
There should be no ``composer.lock`` file.

### CODE REVIEW

**Comment by DRvanR** [comment]
For the record, the composer file is ignored when adding this bundle as a dependency to your project, but it does help ensure the development of the bundle happens with the same dependencies (which is why it was committed). For reference, see the [relevant composer documentation][2]. However, seeing that the bundle has been stable for quite some time now, I don't mind removing the `composer.lock` file.

Thoughts @rjkip?

[2]: https://getcomposer.org/doc/02-libraries.md#lock-file

**Comment by rjkip** [comment]
I like having a composer.lock for the reason you described. I also see no downsides to having a composer.lock. So I see no reason to remove it. Thanks for the effort, though!

**Comment by JHGitty** [comment]
The reason is that the ``composer.lock`` file could be different for each PHP version and Symfony version.

**Comment by DRvanR** [comment]
Thanks for the effort!

**Pull request merged**
